/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6_noheliaeuceda;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author euced
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_nuevaBebida = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_nombreB = new javax.swing.JTextField();
        btn_guardarB = new javax.swing.JButton();
        js_costo = new javax.swing.JSpinner();
        js_tamanio = new javax.swing.JSpinner();
        js_precioB = new javax.swing.JSpinner();
        cb_tipo = new javax.swing.JComboBox<>();
        cb_estado = new javax.swing.JComboBox<>();
        jd_nuevaComida = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cb_tipoC = new javax.swing.JComboBox<>();
        btn_guardarC = new javax.swing.JButton();
        js_precioC = new javax.swing.JSpinner();
        js_costoC = new javax.swing.JSpinner();
        tf_nombreC = new javax.swing.JTextField();
        jd_inventario = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ta_inventario = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        js_indice = new javax.swing.JSpinner();
        btn_modificar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        jd_factura = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_productos = new javax.swing.JList<>();
        btn_imprimirFactura = new javax.swing.JButton();
        tf_nombreF = new javax.swing.JTextField();
        tf_email = new javax.swing.JTextField();
        tf_rtn = new javax.swing.JTextField();
        tf_cai = new javax.swing.JTextField();
        cb_producto = new javax.swing.JComboBox<>();
        btn_cargarProductos = new javax.swing.JButton();
        jd_ventas = new javax.swing.JDialog();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_ventas = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jd_ingresos = new javax.swing.JDialog();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_ingresos = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmi_nose = new javax.swing.JMenu();
        jmi_nuevaB = new javax.swing.JMenuItem();
        jmi_nuevaC = new javax.swing.JMenuItem();
        jm_facturacion = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jmi_ventas = new javax.swing.JMenuItem();
        jmi_ingresos = new javax.swing.JMenuItem();
        jmi_inventario = new javax.swing.JMenuItem();

        jLabel1.setText("Nueva Bebida");

        jLabel2.setText("Nombre");

        jLabel3.setText("Costo");

        jLabel4.setText("Precio");

        jLabel5.setText("Estado");

        jLabel6.setText("Tamaño");

        jLabel7.setText("Tipo");

        btn_guardarB.setText("Guardar");
        btn_guardarB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_guardarBMouseClicked(evt);
            }
        });
        btn_guardarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarBActionPerformed(evt);
            }
        });

        js_costo.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 0.1d));

        js_tamanio.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 0.1d));

        js_precioB.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 0.1d));

        cb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Café", "Té", "Granita" }));

        cb_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Caliente", "Helado", "Yougurt" }));

        javax.swing.GroupLayout jd_nuevaBebidaLayout = new javax.swing.GroupLayout(jd_nuevaBebida.getContentPane());
        jd_nuevaBebida.getContentPane().setLayout(jd_nuevaBebidaLayout);
        jd_nuevaBebidaLayout.setHorizontalGroup(
            jd_nuevaBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_nuevaBebidaLayout.createSequentialGroup()
                .addGroup(jd_nuevaBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_nuevaBebidaLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jd_nuevaBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGroup(jd_nuevaBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_nuevaBebidaLayout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jd_nuevaBebidaLayout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addGroup(jd_nuevaBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(js_precioB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                    .addComponent(js_costo)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_nuevaBebidaLayout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(js_tamanio))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_nuevaBebidaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jd_nuevaBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cb_estado, javax.swing.GroupLayout.Alignment.TRAILING, 0, 146, Short.MAX_VALUE)
                                    .addComponent(tf_nombreB, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cb_tipo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jd_nuevaBebidaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_guardarB)))
                .addGap(99, 99, 99))
        );
        jd_nuevaBebidaLayout.setVerticalGroup(
            jd_nuevaBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_nuevaBebidaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_nuevaBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_nombreB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_nuevaBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(js_costo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_nuevaBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(js_precioB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jd_nuevaBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(cb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_nuevaBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(js_tamanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jd_nuevaBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_guardarB)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel8.setText("Nueva Bebida");

        jLabel9.setText("Nombre");

        jLabel10.setText("Costo");

        jLabel11.setText("Precio");

        jLabel12.setText("Tipo");

        cb_tipoC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dona", "Sandwich", "Crepa" }));

        btn_guardarC.setText("Guardar");
        btn_guardarC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_guardarCMouseClicked(evt);
            }
        });
        btn_guardarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarCActionPerformed(evt);
            }
        });

        js_precioC.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 0.1d));

        js_costoC.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 0.1d));

        javax.swing.GroupLayout jd_nuevaComidaLayout = new javax.swing.GroupLayout(jd_nuevaComida.getContentPane());
        jd_nuevaComida.getContentPane().setLayout(jd_nuevaComidaLayout);
        jd_nuevaComidaLayout.setHorizontalGroup(
            jd_nuevaComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_nuevaComidaLayout.createSequentialGroup()
                .addGroup(jd_nuevaComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_nuevaComidaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_guardarC))
                    .addGroup(jd_nuevaComidaLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jd_nuevaComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jd_nuevaComidaLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(61, 61, 61)
                        .addComponent(cb_tipoC, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68))
            .addGroup(jd_nuevaComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_nuevaComidaLayout.createSequentialGroup()
                    .addGap(74, 74, 74)
                    .addGroup(jd_nuevaComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11))
                    .addGroup(jd_nuevaComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jd_nuevaComidaLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jd_nuevaComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(js_precioC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                .addComponent(js_costoC)))
                        .addGroup(jd_nuevaComidaLayout.createSequentialGroup()
                            .addGap(75, 75, 75)
                            .addGroup(jd_nuevaComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tf_nombreC, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jd_nuevaComidaLayout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addGap(74, 74, 74)))
        );
        jd_nuevaComidaLayout.setVerticalGroup(
            jd_nuevaComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_nuevaComidaLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel9)
                .addGap(96, 96, 96)
                .addGroup(jd_nuevaComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_nuevaComidaLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jd_nuevaComidaLayout.createSequentialGroup()
                        .addComponent(cb_tipoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(btn_guardarC)
                        .addGap(37, 37, 37))))
            .addGroup(jd_nuevaComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_nuevaComidaLayout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(jLabel8)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(tf_nombreC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(jd_nuevaComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(js_costoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jd_nuevaComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11)
                        .addComponent(js_precioC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(171, Short.MAX_VALUE)))
        );

        jLabel13.setText("Inventario");

        ta_inventario.setColumns(20);
        ta_inventario.setRows(5);
        jScrollPane5.setViewportView(ta_inventario);

        jLabel22.setText("Indice a evaluar");

        js_indice.setModel(new javax.swing.SpinnerNumberModel());

        btn_modificar.setText("Modificar");
        btn_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_modificarMouseClicked(evt);
            }
        });

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_inventarioLayout = new javax.swing.GroupLayout(jd_inventario.getContentPane());
        jd_inventario.getContentPane().setLayout(jd_inventarioLayout);
        jd_inventarioLayout.setHorizontalGroup(
            jd_inventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_inventarioLayout.createSequentialGroup()
                .addGroup(jd_inventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_inventarioLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_inventarioLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jd_inventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addGroup(jd_inventarioLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(js_indice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_modificar)
                    .addComponent(btn_eliminar))
                .addGap(63, 63, 63))
        );
        jd_inventarioLayout.setVerticalGroup(
            jd_inventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_inventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_inventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_inventarioLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_inventarioLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jd_inventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jd_inventarioLayout.createSequentialGroup()
                        .addComponent(js_indice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_modificar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_eliminar)))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jLabel14.setText("Factura");

        jLabel15.setText("Nombre Cliente");

        jLabel16.setText("Email");

        jLabel17.setText("RTN");

        jLabel18.setText("CAI");

        jl_productos.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jl_productos);

        btn_imprimirFactura.setText("Imprimir Factura");
        btn_imprimirFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimirFacturaActionPerformed(evt);
            }
        });

        cb_producto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_productoItemStateChanged(evt);
            }
        });
        cb_producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_productoMouseClicked(evt);
            }
        });

        btn_cargarProductos.setText("Cargar Productos");
        btn_cargarProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cargarProductosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_facturaLayout = new javax.swing.GroupLayout(jd_factura.getContentPane());
        jd_factura.getContentPane().setLayout(jd_facturaLayout);
        jd_facturaLayout.setHorizontalGroup(
            jd_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_facturaLayout.createSequentialGroup()
                .addGroup(jd_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_facturaLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jd_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)))
                    .addGroup(jd_facturaLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(jd_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(tf_nombreF, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_cai, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_rtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_facturaLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btn_cargarProductos)
                        .addGap(27, 27, 27)
                        .addComponent(cb_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_facturaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jd_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_facturaLayout.createSequentialGroup()
                        .addComponent(btn_imprimirFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_facturaLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))))
        );
        jd_facturaLayout.setVerticalGroup(
            jd_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_facturaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(jd_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(tf_nombreF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tf_rtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tf_cai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cargarProductos))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btn_imprimirFactura)
                .addContainerGap())
        );

        jLabel19.setText("Ventas Totales");

        ta_ventas.setColumns(20);
        ta_ventas.setRows(5);
        jScrollPane1.setViewportView(ta_ventas);

        jButton1.setText("Cargar Ventas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_ventasLayout = new javax.swing.GroupLayout(jd_ventas.getContentPane());
        jd_ventas.getContentPane().setLayout(jd_ventasLayout);
        jd_ventasLayout.setHorizontalGroup(
            jd_ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ventasLayout.createSequentialGroup()
                .addGroup(jd_ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ventasLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel19))
                    .addGroup(jd_ventasLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ventasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(36, 36, 36))
        );
        jd_ventasLayout.setVerticalGroup(
            jd_ventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ventasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(21, 21, 21))
        );

        jLabel20.setText("Ingresos Totales");

        ta_ingresos.setColumns(20);
        ta_ingresos.setRows(5);
        jScrollPane3.setViewportView(ta_ingresos);

        javax.swing.GroupLayout jd_ingresosLayout = new javax.swing.GroupLayout(jd_ingresos.getContentPane());
        jd_ingresos.getContentPane().setLayout(jd_ingresosLayout);
        jd_ingresosLayout.setHorizontalGroup(
            jd_ingresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ingresosLayout.createSequentialGroup()
                .addGroup(jd_ingresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ingresosLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel20))
                    .addGroup(jd_ingresosLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jd_ingresosLayout.setVerticalGroup(
            jd_ingresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ingresosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("jButton2");

        jmi_nose.setText("Nuevo Producto");

        jmi_nuevaB.setText("Nueva Bebida");
        jmi_nuevaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_nuevaBActionPerformed(evt);
            }
        });
        jmi_nose.add(jmi_nuevaB);

        jmi_nuevaC.setText("Nueva Comida");
        jmi_nuevaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_nuevaCActionPerformed(evt);
            }
        });
        jmi_nose.add(jmi_nuevaC);

        jMenuBar1.add(jmi_nose);

        jm_facturacion.setText("Facturación");
        jm_facturacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jm_facturacionMouseClicked(evt);
            }
        });
        jm_facturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_facturacionActionPerformed(evt);
            }
        });
        jMenuBar1.add(jm_facturacion);

        jMenu1.setText("Otros");

        jmi_ventas.setText("Ventas");
        jmi_ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_ventasActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_ventas);

        jmi_ingresos.setText("Ingresos");
        jmi_ingresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_ingresosActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_ingresos);

        jmi_inventario.setText("Inventario");
        jmi_inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_inventarioActionPerformed(evt);
            }
        });
        jMenu1.add(jmi_inventario);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_guardarBActionPerformed

    private void btn_guardarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarCActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_guardarCActionPerformed

    private void btn_imprimirFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimirFacturaActionPerformed
        // TODO add your handling code here:
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_producto.getModel();
         DefaultListModel modeloL = (DefaultListModel) jl_productos.getModel();
         double total=0, subtotal=0;
        String nombre, email, rtn, cai;
        nombre = tf_nombreF.getText();
        email = tf_email.getText();
        rtn = tf_rtn.getText();
        cai = tf_cai.getText();
        ArrayList<Producto> lista = new ArrayList();
        
        for (int i = 0; i < modeloL.getSize(); i++) {
            lista.add(((Producto)modeloL.getElementAt(i)));
            subtotal +=((Producto)modeloL.getElementAt(i)).getPrecioCosto();
            total +=((Producto)modeloL.getElementAt(i)).getPrecioVenta();
        }
        Ventas v= new Ventas(total, new Date());
        i.Agregar(v);
        Factura fact = new Factura(nombre,email, rtn, cai, new Date());
        fact.setListaP(lista);
        fact.imprimeFactura(this, subtotal, total);
        tf_nombreF.setText("");
        tf_email.setText("");
        tf_rtn.setText("");
        tf_cai.setText("");
        modeloL.clear();
        modelo.removeAllElements();
        
    }//GEN-LAST:event_btn_imprimirFacturaActionPerformed

    private void jmi_nuevaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_nuevaBActionPerformed
        // TODO add your handling code here:
        jd_nuevaBebida.setModal(true);
        jd_nuevaBebida.pack(); //dibuja la ventana a todos los objetos que tiene adentro
        jd_nuevaBebida.setLocationRelativeTo(this); //centra la ventana
        jd_nuevaBebida.setVisible(true);


    }//GEN-LAST:event_jmi_nuevaBActionPerformed

    private void jm_facturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_facturacionActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jm_facturacionActionPerformed

    private void jmi_ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_ventasActionPerformed
        // TODO add your handling code here:
        jd_ventas.setModal(true);
        jd_ventas.pack(); //dibuja la ventana a todos los objetos que tiene adentro
        jd_ventas.setLocationRelativeTo(this); //centra la ventana
        jd_ventas.setVisible(true);
    }//GEN-LAST:event_jmi_ventasActionPerformed

    private void jmi_ingresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_ingresosActionPerformed
        // TODO add your handling code here:
        jd_ingresos.setModal(true);
        jd_ingresos.pack(); //dibuja la ventana a todos los objetos que tiene adentro
        jd_ingresos.setLocationRelativeTo(this); //centra la ventana
        jd_ingresos.setVisible(true);
    }//GEN-LAST:event_jmi_ingresosActionPerformed

    private void btn_guardarBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarBMouseClicked
        // TODO add your handling code here:
        try {

            String nombre, estado, tipo;
            double tamanio, precioCosto, precioVenta;

            nombre = tf_nombreB.getText();
            precioCosto = (double) js_costo.getValue();
            precioVenta = (double) js_precioB.getValue();
            estado = (String) cb_estado.getSelectedItem();
            tamanio = (double) js_tamanio.getValue();
            tipo = (String) cb_tipo.getSelectedItem();
            Bebida b = new Bebida(estado, tamanio, tipo, precioCosto, precioVenta, nombre);
            listaP.add(b);
            inventario.agregar(b);

            tf_nombreB.setText("");
            js_costo.setValue(0);
            js_precioB.setValue(0);
            cb_estado.setSelectedIndex(0);
            js_tamanio.setValue(0);
            cb_tipo.setSelectedIndex(0);
            JOptionPane.showMessageDialog(jd_nuevaBebida, "Agregado con exito");
            jd_nuevaBebida.setVisible(false);

        } catch (Exception e) {
            System.out.println(e.getMessage());
            e.printStackTrace();

            JOptionPane.showMessageDialog(jd_nuevaBebida, "No se pudo agregar");

        }
    }//GEN-LAST:event_btn_guardarBMouseClicked

    private void btn_guardarCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarCMouseClicked
        // TODO add your handling code here:
        try {
            String nombre, tipo;
            double precioCosto, precioVenta;

            nombre = tf_nombreC.getText();
            precioCosto = (double) js_costoC.getValue();
            precioVenta = (double) js_precioC.getValue();
            tipo = (String) cb_tipo.getSelectedItem();
            Comida c = new Comida(tipo, precioCosto, precioVenta, nombre);
            listaP.add(c);
            System.out.println(c);
            inventario.agregar(c);

            tf_nombreC.setText("");
            js_costoC.setValue(0);
            js_precioC.setValue(0);
            cb_tipoC.setSelectedIndex(0);
            JOptionPane.showMessageDialog(jd_nuevaBebida, "Agregado con exito");
            jd_nuevaComida.setVisible(false);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(jd_nuevaBebida, "No se pudo agregar");

        }
    }//GEN-LAST:event_btn_guardarCMouseClicked

    private void jmi_inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_inventarioActionPerformed
        try {
            inventario.escribirArchivo();
        } catch (IOException ex) {
        }
        inventario.cargarArchivo();
        String salida = inventario.cargarArchivo();
        ta_inventario.setText(salida);

        jd_inventario.setModal(true);
        jd_inventario.pack(); //dibuja la ventana a todos los objetos que tiene adentro
        jd_inventario.setLocationRelativeTo(this); //centra la ventana
        jd_inventario.setVisible(true);
    }//GEN-LAST:event_jmi_inventarioActionPerformed

    private void jm_facturacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jm_facturacionMouseClicked
        // TODO add your handling code here:
        jd_factura.setModal(true);
        jd_factura.pack(); //dibuja la ventana a todos los objetos que tiene adentro
        jd_factura.setLocationRelativeTo(this); //centra la ventana
        jd_factura.setVisible(true);
    }//GEN-LAST:event_jm_facturacionMouseClicked

    private void btn_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificarMouseClicked
        // TODO add your handling code here:
        try {
            inventario.escribirArchivo();
            int i = (Integer) js_indice.getValue();
            String nombre;
            double c, v;
            if (i >= 0) {
                nombre = JOptionPane.showInputDialog("Ingrese nuevo nombre");
                c = Integer.parseInt(JOptionPane.showInputDialog("Ingrese nuevo Precio de costo"));
                v = Integer.parseInt(JOptionPane.showInputDialog("Ingrese nuevo Precio de venta"));
                inventario.lista.get(i).setNombre(nombre);
                inventario.lista.get(i).setPrecioCosto(c);
                inventario.lista.get(i).setPrecioVenta(v);

                inventario.cargarArchivo();
                String salida = inventario.cargarArchivo();
                ta_inventario.setText(salida);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jd_inventario, "No se pudo modificar");
        }

    }//GEN-LAST:event_btn_modificarMouseClicked

    private void btn_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMouseClicked
        // TODO add your handling code here:
        try {
            inventario.escribirArchivo();
            int i = (Integer) js_indice.getValue();
            if (i >= 0) {
                inventario.lista.remove(i);

                inventario.cargarArchivo();
                String salida = inventario.cargarArchivo();
                ta_inventario.setText(salida);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(jd_inventario, "No se pudo eliminar");
        }
    }//GEN-LAST:event_btn_eliminarMouseClicked

    private void btn_cargarProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cargarProductosMouseClicked
        // TODO add your handling code here:
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_producto.getModel();
        for (Producto producto : inventario.lista) {
            modelo.addElement(producto);
        }

        cb_producto.setModel(modelo);
    }//GEN-LAST:event_btn_cargarProductosMouseClicked

    private void cb_productoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_productoMouseClicked
        
    }//GEN-LAST:event_cb_productoMouseClicked

    private void cb_productoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_productoItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange()==1) {
            DefaultListModel modeloL = (DefaultListModel) jl_productos.getModel();
            modeloL.addElement(cb_producto.getSelectedItem());
            
        }
    }//GEN-LAST:event_cb_productoItemStateChanged

    private void jmi_nuevaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_nuevaCActionPerformed
        // TODO add your handling code here:
        jd_nuevaComida.setModal(true);
        jd_nuevaComida.pack(); //dibuja la ventana a todos los objetos que tiene adentro
        jd_nuevaComida.setLocationRelativeTo(this); //centra la ventana
        jd_nuevaComida.setVisible(true);
    }//GEN-LAST:event_jmi_nuevaCActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            i.escribirArchivo();
        } catch (IOException ex) {
        }
        i.cargarArchivo();
        String salida = i.cargarArchivo();
        ta_ingresos.setText(salida);

        jd_ingresos.setModal(true);
        jd_ingresos.pack(); //dibuja la ventana a todos los objetos que tiene adentro
        jd_ingresos.setLocationRelativeTo(this); //centra la ventana
        jd_ingresos.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cargarProductos;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_guardarB;
    private javax.swing.JButton btn_guardarC;
    private javax.swing.JButton btn_imprimirFactura;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JComboBox<String> cb_estado;
    private javax.swing.JComboBox<String> cb_producto;
    private javax.swing.JComboBox<String> cb_tipo;
    private javax.swing.JComboBox<String> cb_tipoC;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JDialog jd_factura;
    private javax.swing.JDialog jd_ingresos;
    private javax.swing.JDialog jd_inventario;
    private javax.swing.JDialog jd_nuevaBebida;
    private javax.swing.JDialog jd_nuevaComida;
    private javax.swing.JDialog jd_ventas;
    private javax.swing.JList<String> jl_productos;
    private javax.swing.JMenu jm_facturacion;
    private javax.swing.JMenuItem jmi_ingresos;
    private javax.swing.JMenuItem jmi_inventario;
    private javax.swing.JMenu jmi_nose;
    private javax.swing.JMenuItem jmi_nuevaB;
    private javax.swing.JMenuItem jmi_nuevaC;
    private javax.swing.JMenuItem jmi_ventas;
    private javax.swing.JSpinner js_costo;
    private javax.swing.JSpinner js_costoC;
    private javax.swing.JSpinner js_indice;
    private javax.swing.JSpinner js_precioB;
    private javax.swing.JSpinner js_precioC;
    private javax.swing.JSpinner js_tamanio;
    private javax.swing.JTextArea ta_ingresos;
    private javax.swing.JTextArea ta_inventario;
    private javax.swing.JTextArea ta_ventas;
    private javax.swing.JTextField tf_cai;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_nombreB;
    private javax.swing.JTextField tf_nombreC;
    private javax.swing.JTextField tf_nombreF;
    private javax.swing.JTextField tf_rtn;
    // End of variables declaration//GEN-END:variables
    ArrayList<Producto> listaP = new ArrayList();
    Inventario inventario = new Inventario("./inventario.txt");
    Ingreso i = new Ingreso("./ingreso.txt");
}
